# Generated by Django 4.0.10 on 2024-12-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_recipiant_account_transaction_recipient_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactions_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
